### ISSUE TITLE
Treetop parser can't match if ass contain encoding BOM

### ISSUE THREAD

**Issue by lenage** [simonrepp/titlekit#1]
`titlekit` is a great gem to handle ass file, but it doesn't work for Aegisub generated subtitle files because of it contain encoding BOM.

```bash
cat -A example.ass

M-oM-;M-?[Script Info]$
; Script generated by Aegisub 3.2.2$
; http://www.aegisub.org/$
Title: Default Aegisub file$
ScriptType: v4.00+$
WrapStyle: 0$
ScaledBorderAndShadow: yes$
YCbCr Matrix: None$
```

ASS parser will be failed cause file include `M-oM-;M-?`, so when read file content, maybe you could specify encoding like:

``` ruby
string = File.read(file_path, encoding: 'bom|utf-8')
```

**Comment by simonrepp** [comment]
Hey, thanks for the report and glad to hear the gem is of use for you!
I'll look into writing a test and integrating your propsed fix as soon as i get to it.
If there's no problems along the way a new release with the fix should be up in the next days sometime :)

Cheers!

**Comment by simonrepp** [comment]
Ok so I wrote a spec and fixed it (https://github.com/simonrepp/titlekit/commit/529ef96c4869e92d91fc3b0abb6183c2e4b955a1) , please pull the lastest commit and give it a try - let me know if it works for you, then I'll release a new version of the gem.

(Small note: Your proposed fix didn't work for me, there's only one place where File.read is used, but that's where the file is read to determine the encoding via heuristics, not where it gets fed into Treetop. (Also adding the encoding flag led to the output being spammed with warnings during running specs) I solved the bom issue by adding an optional occurance of the utf8 bom to the ass treetop grammar instead.)

**Comment by lenage** [comment]
Thank you @simonrepp , I'm trying it now, will let you know when its done. Thanks again

**Comment by lenage** [comment]
Hi @simonrepp , I just replace `bom.ass` file with my and run `rake`, seems didn't work well for me, see output

```
Failures:

  1) Titlekit::ASS.import with a file including a BOM parses and builds 2 subtitles
     Failure/Error: Titlekit::ASS.import(File.read('spec/files/ass/bom.ass'))
     RuntimeError:
       failure_index 184
       failure_line 10
       failure_column 1
       failure_reason Expected one of "\r\n", "\n", "\r", '[V4+ Styles]', '[Events]' at line 10, column 1 (byte 185) after ﻿[Script Info]
       ; Script generated by Aegisub 3.2.2
       ; http://www.aegisub.org/
       Title: Default Aegisub file
       ScriptType: v4.00+
       WrapStyle: 0
       ScaledBorderAndShadow: yes
       YCbCr Matrix: None
     # ./lib/titlekit/parsers/ass.rb:62:in `import'
     # ./spec/ass_spec.rb:55:in `block (4 levels) in <top (required)>'
     # ./spec/ass_spec.rb:59:in `block (4 levels) in <top (required)>'

  2) Titlekit::ASS.import with a file including a BOM parses and builds correct ids
     Failure/Error: Titlekit::ASS.import(File.read('spec/files/ass/bom.ass'))
     RuntimeError:
       failure_index 184
       failure_line 10
       failure_column 1
       failure_reason Expected one of "\r\n", "\n", "\r", '[V4+ Styles]', '[Events]' at line 10, column 1 (byte 185) after ﻿[Script Info]
       ; Script generated by Aegisub 3.2.2
       ; http://www.aegisub.org/
       Title: Default Aegisub file
       ScriptType: v4.00+
       WrapStyle: 0
       ScaledBorderAndShadow: yes
       YCbCr Matrix: None
     # ./lib/titlekit/parsers/ass.rb:62:in `import'
     # ./spec/ass_spec.rb:55:in `block (4 levels) in <top (required)>'
     # ./spec/ass_spec.rb:63:in `block (4 levels) in <top (required)>'

  3) Titlekit::ASS.import with a file including a BOM parses and builds correct timecodes
     Failure/Error: Titlekit::ASS.import(File.read('spec/files/ass/bom.ass'))
     RuntimeError:
       failure_index 184
       failure_line 10
       failure_column 1
       failure_reason Expected one of "\r\n", "\n", "\r", '[V4+ Styles]', '[Events]' at line 10, column 1 (byte 185) after ﻿[Script Info]
       ; Script generated by Aegisub 3.2.2
       ; http://www.aegisub.org/
       Title: Default Aegisub file
       ScriptType: v4.00+
       WrapStyle: 0
       ScaledBorderAndShadow: yes
       YCbCr Matrix: None
     # ./lib/titlekit/parsers/ass.rb:62:in `import'
     # ./spec/ass_spec.rb:55:in `block (4 levels) in <top (required)>'
     # ./spec/ass_spec.rb:67:in `block (4 levels) in <top (required)>'

  4) Titlekit::ASS.import with a file including a BOM parses and builds correct lines
     Failure/Error: Titlekit::ASS.import(File.read('spec/files/ass/bom.ass'))
     RuntimeError:
       failure_index 184
       failure_line 10
       failure_column 1
       failure_reason Expected one of "\r\n", "\n", "\r", '[V4+ Styles]', '[Events]' at line 10, column 1 (byte 185) after ﻿[Script Info]
       ; Script generated by Aegisub 3.2.2
       ; http://www.aegisub.org/
       Title: Default Aegisub file
       ScriptType: v4.00+
       WrapStyle: 0
       ScaledBorderAndShadow: yes
       YCbCr Matrix: None
     # ./lib/titlekit/parsers/ass.rb:62:in `import'
     # ./spec/ass_spec.rb:55:in `block (4 levels) in <top (required)>'
     # ./spec/ass_spec.rb:72:in `block (4 levels) in <top (required)>'

  5) Titlekit::Job Simultaneous Subtitles with three+ simultaneous subtitles exporting to SRT delivers the expected output
     Failure/Error: expect(FileUtils.compare_file(@out, @expected)).to be true
       
       expected true
            got false
     # ./spec/simultaneous_subtitles/simultaneous_subtitles_spec.rb:173:in `block (5 levels) in <top (required)>'

  6) Titlekit::Job Simultaneous Subtitles with three+ simultaneous subtitles exporting to SSA delivers the expected output
     Failure/Error: expect(FileUtils.compare_file(@out, @expected)).to be true
       
       expected true
            got false
     # ./spec/simultaneous_subtitles/simultaneous_subtitles_spec.rb:194:in `block (5 levels) in <top (required)>'

  7) Titlekit::Job Simultaneous Subtitles with three+ simultaneous subtitles exporting to ASS delivers the expected output
     Failure/Error: expect(FileUtils.compare_file(@out, @expected)).to be true
       
       expected true
            got false
     # ./spec/simultaneous_subtitles/simultaneous_subtitles_spec.rb:215:in `block (5 levels) in <top (required)>'

Finished in 12.95 seconds (files took 0.24865 seconds to load)
148 examples, 7 failures

Failed examples:

rspec ./spec/ass_spec.rb:58 # Titlekit::ASS.import with a file including a BOM parses and builds 2 subtitles
rspec ./spec/ass_spec.rb:62 # Titlekit::ASS.import with a file including a BOM parses and builds correct ids
rspec ./spec/ass_spec.rb:66 # Titlekit::ASS.import with a file including a BOM parses and builds correct timecodes
rspec ./spec/ass_spec.rb:71 # Titlekit::ASS.import with a file including a BOM parses and builds correct lines
rspec ./spec/simultaneous_subtitles/simultaneous_subtitles_spec.rb:172 # Titlekit::Job Simultaneous Subtitles with three+ simultaneous subtitles exporting to SRT delivers the expected output
rspec ./spec/simultaneous_subtitles/simultaneous_subtitles_spec.rb:193 # Titlekit::Job Simultaneous Subtitles with three+ simultaneous subtitles exporting to SSA delivers the expected output
rspec ./spec/simultaneous_subtitles/simultaneous_subtitles_spec.rb:214 # Titlekit::Job Simultaneous Subtitles with three+ simultaneous subtitles exporting to ASS delivers the expected output
```

Here is my file: https://gist.github.com/lenage/edea3c060a534563f2dd

Thanks again for the fix

**Comment by lenage** [comment]
Since new error not related with UTF8 BOM, so i closing this issue for now.

**Comment by simonrepp** [comment]
Hey @lenage,

Thanks for trying it out!
Half of the errors you got were to be expected because the specs are written to work with the specific file I prepared. As for the other half I am not quite sure, kinda hard to do a remote diagnosis without having the file. - If you provide me with your file I can look further into this, but please make sure to let me have a byte-accurate copy (that is I need the file 1:1 for download, no pasting the content ;)).

If not I'll just release what I have now sometime next week!

Thanks again for your report and cooperation :)

**Comment by simonrepp** [comment]
I just released the new version!
https://github.com/simonrepp/titlekit/tree/v1.2.2

Case closed. :)

**Comment by lenage** [comment]
Thanks, using `v1.2.2` now :)
